//PREGUNTA 2
ALTER SYSTEM SET "WALLET_ROOT"='C:\app\alumnos\admin\orcl\xdb_wallet' scope=SPFILE;

ALTER SYSTEM SET TDE_CONFIGURATION="KEYSTORE_CONFIGURATION=FILE" scope=both;

//PREGUNTA 3
CREATE USER LIFEFIT IDENTIFIED BY LIFEFIT123
    DEFAULT TABLESPACE TS_LIFEFIT
    QUOTA UNLIMITED ON TS_LIFEFIT;
GRANT CREATE TABLE, CONNECT TO LIFEFIT;

//PREGUNTA 6

SELECT * FROM dba_encrypted_columns;

//PREGUNTA 4 Y 5
CREATE TABLE CLIENTE(
    DNI VARCHAR2(16) PRIMARY KEY,
    NOMBRE VARCHAR2(16) ENCRYPT NOT NULL,
    APELLIDO VARCHAR2(16) NOT NULL,
    TELEFONO VARCHAR2(16) ENCRYPT NOT NULL);

COMMIT;